

export const ActionTypes ={
    SET_TASK : "SET_TASK",
    SELECTED_TASK: "SELECTED_TASK",
    REMOVE_SELECTED_TASK: "REMOVE_SELECTED_TASK",
    ADD_TASK:"ADD_TASK",
    EDIT_SELECTED_TASK: "EDIT_SELECTED_TASK"
}